feat: 更新 deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,12 +19,12 @@ jobs:
 
       - name: Deploy seckill docker
         run: |
-          ssh ubuntu@$SERVER_IP "cd ~/seckill/docker && docker compose down"
+          ssh ubuntu@${{ secrets.SERVER_IP }} "cd ~/seckill/docker && docker compose down"
           scp -r ./seckill-docker/* ubuntu@${{ secrets.SERVER_IP }}:~/seckill/docker
-          ssh ubuntu@$SERVER_IP "cd ~/seckill/docker && docker compose up -d"
+          ssh ubuntu@${{ secrets.SERVER_IP }} "cd ~/seckill/docker && docker compose up -d"
 
       - name: Deploy seckill nginx
         run: |
-          ssh ubuntu@$SERVER_IP "cd ~/seckill/nginx && /usr/local/openresty/nginx/sbin/nginx -p \$(pwd) -s stop" || echo "nginx stop failed"
+          ssh ubuntu@${{ secrets.SERVER_IP }} "cd ~/seckill/nginx && /usr/local/openresty/nginx/sbin/nginx -p \$(pwd) -s stop" || echo "nginx stop failed"
           scp -r ./seckill-nginx/* ubuntu@${{ secrets.SERVER_IP }}:~/seckill/nginx
-          ssh ubuntu@$SERVER_IP "cd ~/seckill/nginx && /usr/local/openresty/nginx/sbin/nginx -p \$(pwd) -c conf/nginx.conf"
+          ssh ubuntu@${{ secrets.SERVER_IP }} "cd ~/seckill/nginx && /usr/local/openresty/nginx/sbin/nginx -p \$(pwd) -c conf/nginx.conf"
